# fly.toml app configuration file generated for sveltekit-and-turso-analytics on 2023-12-10T21:09:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sveltekit-and-turso-analytics"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
